/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parabola;

/**
 *
 * @author Ahg3L
 */
public class ventanita extends javax.swing.JFrame {
    
    private final lienzo milienzo;
    
    public ventanita() {
        initComponents();
        milienzo = new lienzo();
        add (milienzo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area1 = new javax.swing.JTextField();
        area2 = new javax.swing.JTextField();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        area1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1ActionPerformed(evt);
            }
        });

        area2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2ActionPerformed(evt);
            }
        });

        boton.setText("Empezar");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(area2, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(area1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton)
                    .addComponent(area1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(area2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1ActionPerformed
        try { 
        double velocidad = Double.parseDouble(area1.getText()); 
        javax.swing.JOptionPane.showMessageDialog(this, "Velocidad ingresada: " + velocidad + " m/s");
        } catch (NumberFormatException e) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingresa un número válido en velocidad."); 
        }
    }//GEN-LAST:event_area1ActionPerformed

    private void area2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2ActionPerformed
        try { 
            double theta = Double.parseDouble(area2.getText()); 

            if(theta > 90){
                javax.swing.JOptionPane.showMessageDialog(this, 
                "El angulo no puede ser mayor a 90 grados.");
                area2.setText("");
                return;
            }

            javax.swing.JOptionPane.showMessageDialog(this, 
            "Ángulo ingresado: " + theta + "°");
        
        } catch (NumberFormatException e) { 
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor ingresa un número válido en theta."); 
        }
    }//GEN-LAST:event_area2ActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        try { 
        
            double velocidad = Double.parseDouble(area1.getText());
            double theta = Double.parseDouble(area2.getText());

            if(theta > 90){
                javax.swing.JOptionPane.showMessageDialog(this, 
                "El angulo no puede ser mayor a 90 grados.");
                return;
            }

            milienzo.setParametros(velocidad, theta);  
        
        } catch (NumberFormatException e) {       
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor ingresa números válidos en ambos campos.");
        }
    }//GEN-LAST:event_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {   
        java.awt.EventQueue.invokeLater(() -> new ventanita().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area1;
    private javax.swing.JTextField area2;
    private javax.swing.JButton boton;
    // End of variables declaration//GEN-END:variables
}
