/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.evalfuncion;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahg3L
 */
public class evaluarfuncion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(evaluarfuncion.class.getName());

    /**
     * Creates new form evaluarfuncion
     */
    public evaluarfuncion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        boton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area2.setColumns(20);
        area2.setRows(5);
        jScrollPane1.setViewportView(area2);

        boton2.setText("resolver");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton2)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(boton2)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        
        String cStr = JOptionPane.showInputDialog(this, "Ingrese el valor de la constante C:");
        if (cStr == null) return;
        double c = Double.parseDouble(cStr);

        String xInicialStr = JOptionPane.showInputDialog(this, "Ingrese el valor inicial de x:");
        if (xInicialStr == null) return;
        double xInicial = Double.parseDouble(xInicialStr);

        String xFinalStr = JOptionPane.showInputDialog(this, "Ingrese el valor final de x:");
        if (xFinalStr == null) return;
        double xFinal = Double.parseDouble(xFinalStr);
        
        String incrementoStr = JOptionPane.showInputDialog(this, "Ingrese el incremento (ej: 1, 0.5, 0.1):");
        if (incrementoStr == null) return;
        double incremento = Double.parseDouble(incrementoStr);

        // Validaciones de entrada
        if (xInicial > xFinal) {
            JOptionPane.showMessageDialog(this, "El valor inicial de x no puede ser mayor que el valor final.", "Error de Lógica", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (incremento <= 0) {
            JOptionPane.showMessageDialog(this, "El incremento debe ser un número positivo.", "Error de Lógica", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Encabezado en el área de texto
        area2.setText(""); 
        area2.append("Evaluando la función: y = 4x² - 6x + " + c + "\n");
        area2.append("Desde x = " + xInicial + " hasta x = " + xFinal + " con incremento de " + incremento + "\n");
        area2.append("--------------------------------------------------\n");
        area2.append("  x\t\t  y\n"); // Encabezados de la tabla
        area2.append("--------------------------------------------------\n");

        // Bucle para calcular y mostrar los valores
        for (double x = xInicial; x <= xFinal; x += incremento) {
            // Fórmula: y = 4x^2 - 6x + C
            double y = (4 * x * x) - (6 * x) + c;
            
            // Formato con 2 decimales
            String linea = String.format("x = %.2f\t\ty = %.2f\n", x, y);
            area2.append(linea);
        }

 
    
    }//GEN-LAST:event_boton2ActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(() -> new evaluarfuncion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area2;
    private javax.swing.JButton boton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
